const productsList = [
  {
    id_product: 1,
    category: "nacional",
    fk_idcategorys: 1,
    name_product: "São Paulo 2020",
    price: 300,
    image: "./images/spfc.png",
    id_categorys: 1,
    name_categorys: "Clubes brasileiros",
    selected: false,
  },
  {
    id_product: 2,
    category: "nacional",
    fk_idcategorys: 1,
    name_product: "Palmeiras 2020",
    price: 350,
    image: "./images/palmeiras.png",
    id_categorys: 1,
    name_categorys: "Clubes brasileiros",
    selected: false,
  },
  {
    id_product: 9,
    category: "nacional",
    fk_idcategorys: 1,
    name_product: "Grêmio 2020",
    price: 230,
    image: "./images/gremio.png",
    id_categorys: 1,
    name_categorys: "Clubes brasileiros",
    selected: false,
  },
  {
    id_product: 4,
    category: "europeu",
    fk_idcategorys: 2,
    name_product: "Arsenal 2020/21",
    price: 399.99,
    image: "./images/arsenal.png",
    id_categorys: 2,
    name_categorys: "Clubes europeus",
    selected: false,
  },
  {
    id_product: 10,
    category: "europeu",
    fk_idcategorys: 2,
    name_product: "Manchester City",
    price: 350.99,
    image: "./images/man-city.png",
    id_categorys: 2,
    name_categorys: "Clubes europeus",
    selected: false,
  },
  {
    id_product: 11,
    category: "europeu",
    fk_idcategorys: 2,
    name_product: "Milan 2020/21",
    price: 299.99,
    image: "./images/milan.png",
    id_categorys: 2,
    name_categorys: "Clubes europeus",
    selected: false,
  },
  {
    id_product: 6,
    category: "historica",
    fk_idcategorys: 3,
    name_product: "Brasil 1994",
    price: 200,
    image: "./images/brasil94.png",
    id_categorys: 3,
    name_categorys: "Camisas históricas",
    selected: false,
  },
  {
    id_product: 7,
    category: "historica",
    fk_idcategorys: 3,
    name_product: "Flamengo 1981",
    price: 450,
    image: "./images/fla81.png",
    id_categorys: 3,
    name_categorys: "Camisas históricas",
    selected: false,
  },
  {
    id_product: 3,
    category: "selecao",
    fk_idcategorys: 4,
    name_product: "Alemanha 2020",
    price: 350,
    image: "./images/alemanha.png",
    id_categorys: 4,
    name_categorys: "Seleções nacionais",
    selected: false,
  },
  {
    id_product: 5,
    category: "selecao",
    fk_idcategorys: 4,
    name_product: "Brasil 2020",
    price: 399,
    image: "./images/brasil.png",
    id_categorys: 4,
    name_categorys: "Seleções nacionais",
    selected: false,
  },
  {
    id_product: 8,
    category: "casual",
    fk_idcategorys: 5,
    name_product: "Flamengo T 2020",
    price: 180,
    image: "./images/fla_treino.png",
    id_categorys: 5,
    name_categorys: "Casuais",
    selected: false,
  },
  {
    id_product: 12,
    category: "casual",
    fk_idcategorys: 5,
    name_product: "Real Madrid 2019/20",
    price: 189.99,
    image: "./images/real_treino.png",
    id_categorys: 5,
    name_categorys: "Casuais",
    selected: false,
  },
];

export default productsList;
